### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Xeroxxx** [concurrencylabs/aws-cost-analysis#11]
Hello,
I'm getting the following error with python 3.6.5. It doesn't matter if I'm running it with or w/o parameters.

Can anyone help me with this?

`Traceback (most recent call last):
  File "report_utils.py", line 7, in <module>
    import awscostusageprocessor.processor as cur
  File "/home/marcel/Desktop/AWS/aws-cost-analysis/awscostusageprocessor/processor.py", line 109
    print "Number of records: [{}]".format(record_count)
                                  ^
SyntaxError: invalid syntax
`

Cheers

**Comment by concurrencylabs** [comment]
Hi, thanks for trying out this repo. The codebase currently doesn't support Python 3.x. It supports 2.7. I'll keep this issue open until we upgrade to Python 3. As a workaround, you can create a virtualenv using Python 2.7 when running locally.

**Comment by Xeroxxx** [comment]
Thank you, I will try python 2.7
