### ISSUE TITLE
Limit permissions asked for miserbot

### ISSUE THREAD

**Issue by Sytten** [concurrencylabs/aws-cost-analysis#16]
I don't know if people realize that the permissions give readonly access to a LOT of stuff including secrets...
I would be appreciated if you could limit those permissions to only what is necessary for the bot to operate.

**Comment by concurrencylabs** [comment]
Thank you for your comment. The bot also performs analysis on cost optimizations, for which it needs to have some degree of read access. We will take a closer look and restrict the policy to deny access on operations that are not necessary for cost optimization analysis. In the meanwhile, this repository is not used to keep track of MiserBot issues. We will add this issue to our backlog. If you'd like to follow up on this, please feel free to contact us at support@concurrencylabs.com
