### ISSUE TITLE
Missing cloudformation/process-cur-sam.yml

### ISSUE THREAD

**Issue by schnoddelbotz** [concurrencylabs/aws-cost-analysis#2]
The README mentions a `cloudformation/process-cur-sam.yml` which sounds very helpful ... but it's missing in the repository. Could you add it?

Thanks for sharing these tools!

**Comment by concurrencylabs** [comment]
Thanks for reporting this issue. Our bad, we forgot to include the SAM template in the repo. We just added it, hope you find it useful!
