### ISSUE TITLE
utils.py:get_period_prefix() creates wrong prefix for december

### ISSUE THREAD

**Issue by schnoddelbotz** [concurrencylabs/aws-cost-analysis#4]
Executing:
['python', 'report_utils.py', '--action=prepare-quicksight', '--source-bucket=foo', '--source-prefix=reports/cost-reports/', '--dest-bucket=bar', '--dest-prefix=quicksight/', '--year=2017', '--month=12']

Errors out:
Exception message:[Could not find manifest file in bucket:[foo], prefix:[reports/cost-reports/20171201-20171301/]]

Just increasing int(month) doesn't seem sufficient ;)

**Comment by concurrencylabs** [comment]
Thanks for bringing this up. We were just about to push a fix the same minute this issue was created. Talk about perfect timing  :)  Check out the latest commit:  e977834efcb07f4768bcca0be1b2db353d0a21a2
